language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
after_success:
  - ./scripts/dotnet-publish.sh
  - ./scripts/docker-publish.sh
notifications:
  email:
    on_success: never
    on_failure: always