@url = http://localhost:5000
@payload = Ciao

### Single check
GET {{url}}/ping

### Build a qrcode
GET {{url}}/BuildQrCode?payload={{payload}}

### Read a qrcode printed into an image
POST {{url}}/findQrCode
Content-Type: application/json
{

  "fullname": "John Doe",
  "address": "New York City, Street XYZ"
}