services:

  barcode-builder:
    image: genocs/barcode-builder:local
    hostname: barcode-builder
    container_name: barcode-builder
    ports:
      - 5070:8080
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      logger__console__enabled: "true"
    networks:
      - genocs      

networks:
  genocs:
    name: genocs-network
    external: true
    driver: bridge
