<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.BarcodeLibrary</PackageId>
        <RootNamespace>Genocs.BarcodeLibrary</RootNamespace>
        <AssemblyName>Genocs.BarcodeLibrary</AssemblyName>
        <Title>Library to build Barcodes for .NET Core projects.</Title>
        <Description>QRCode library for .NET Core.</Description>
        <PackageTags>genocs barcode</PackageTags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="4.153.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.153.1" />
        <PackageReference Include="System.Text.Json" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Genocs.BarcodeLibrary.UnitTests" />
    </ItemGroup>
</Project>
