<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.BarcodeLibrary</PackageId>
        <RootNamespace>Genocs.BarcodeLibrary</RootNamespace>
        <AssemblyName>Genocs.BarcodeLibrary</AssemblyName>
        <Title>Library to build Barcodes for .NET Core projects.</Title>
        <Description>QRCode library for .NET Core.</Description>
        <LangVersion>10.0</LangVersion>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <MinClientVersion>5.0.0</MinClientVersion>
        <PackageProjectUrl>https://github.com/Genocs/qrcode.git</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Genocs/qrcode.git</RepositoryUrl>
        <PackageIcon>icon.png</PackageIcon>
        <RepositoryType>git</RepositoryType>
        <PackageTags>barcode reader writer</PackageTags>
        <PackageReleaseNotes>Removed reference</PackageReleaseNotes>
        <PackageReadmeFile>README_NUGET.md</PackageReadmeFile>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <AnalysisLevel>latest</AnalysisLevel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="4.151.1" />
        <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="4.151.1" />
        <PackageReference Include="System.Text.Json" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Genocs.BarcodeLibrary.UnitTests" />
    </ItemGroup>
</Project>
