namespace Genocs.QRCodeLibrary.Encoder;

public abstract class AbstractQRCode : IDisposable
{
    protected QRCodeData QrCodeData { get; set; }

    protected bool _disposed;

    protected AbstractQRCode(QRCodeData data)
    {
        QrCodeData = data;
    }

    /// <summary>
    /// Set a QRCodeData object that will be used to generate QR code. Used in COM Objects connections.
    /// </summary>
    /// <param name="data">Need a QRCodeData object generated by QRCodeGenerator.CreateQrCode().</param>
    virtual public void SetQRCodeData(QRCodeData data)
    {
        QrCodeData = data;
    }

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    protected virtual void Dispose(bool disposing)
    {
        if (!_disposed)
        {
            if (disposing)
            {
                // Free managed resources
                QrCodeData?.Dispose();
            }

            // Free unmanaged resources
            _disposed = true;
        }
    }

    ~AbstractQRCode()
    {
        Dispose(false);
    }
}