<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <PackageId>Genocs.BarcodeLibrary.UnitTests</PackageId>
        <RootNamespace>Genocs.BarcodeLibrary.UnitTests</RootNamespace>
        <AssemblyName>Genocs.BarcodeLibrary.UnitTests</AssemblyName>
        <IsPublishable>false</IsPublishable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\BarcodeLibrary\BarcodeLibrary.csproj" />
        <ProjectReference Include="..\..\QRCodeLibrary\QRCodeLibrary.csproj" />
    </ItemGroup>

</Project>
